<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <RootNamespace>FSO.Common.Domain</RootNamespace>
    <AssemblyName>FSO.Common.Domain</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5-preview.2" />
    <PackageReference Include="Ninject" Version="3.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FSO.Server.Protocol\FSO.Server.Protocol.csproj" />
    <ProjectReference Include="..\tso.content\FSO.Content.csproj" />
  </ItemGroup>

</Project>
