#!/usr/bin/env python3
"""
Generate convention declaration skeletons for freeso-embodiment.

Reads the verb table from docs/design/verb-catalog.md and emits one JSON per op
with only the fields that the convention framework requires to register. Argument
shapes are deliberately empty — d87-d-* children will populate real schemas when
they land handlers.

Run from the sidecar directory:
    python3 conventions/_gen.py           # generate JSON skeletons
    python3 conventions/_gen.py --manifest  # emit docs/ops/verb-manifest.md
"""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[3]
CATALOG = REPO_ROOT / "docs" / "design" / "verb-catalog.md"
MANIFEST_OUT = REPO_ROOT / "docs" / "ops" / "verb-manifest.md"

# Ops explicitly subsumed by others per the catalog text (excluded from generation).
EXCLUDED = {"find-lot"}

# Soul-relevant families — the set an embodied agent actually uses.
# "naming" is listed as a logical grouping but maps to the "memory" JSON family.
SOUL_FAMILIES = {
    "movement",
    "queries",
    "interaction",
    "social",
    "navigation",
    "naming",
    "memory",
    "avatar",
    "build-buy-catalog",
    "property",
    "batch",
}

# Display order for the manifest (soul families only, presentation order).
# "batch" goes last because batch-build composes the build-buy-catalog ops —
# agents read the primitives first, then learn they can pipeline them.
FAMILY_ORDER = [
    "movement",
    "navigation",
    "interaction",
    "social",
    "queries",
    "memory",
    "avatar",
    "property",
    "build-buy-catalog",
    "batch",
]


def parse_catalog(text: str):
    """Extract (op_name, description, family) rows from all markdown tables."""
    ops = []
    seen = set()
    for line in text.splitlines():
        if not line.startswith("| "):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3:
            continue
        op = cells[0]
        if op in ("op_name", ":---", "---"):
            continue
        if not re.match(r"^[a-z][a-z0-9-]+$", op):
            continue
        if op in EXCLUDED or op in seen:
            continue
        description = cells[1]
        family = cells[2]
        ops.append((op, description, family))
        seen.add(op)
    return ops


def write_decl(op: str, description: str, family: str):
    decl = {
        "convention": "freeso-embodiment",
        "version": "1.0",
        "operation": op,
        "family": family,
        "description": description,
        "args": [],
        "produces_tags": [
            {"tag": f"freeso:{op}", "cardinality": "exactly_one"}
        ],
        "antecedents": "none",
        "signing": "member_key",
        "rate_limit": {"max": 30, "per": "sender", "window": "1m"},
        "response": "sync",
        "status": "scaffold",
    }
    out = HERE / f"{op}.json"
    out.write_text(json.dumps(decl, indent=2) + "\n")


def _first_sentence(text: str) -> str:
    """Return the first sentence of a description string."""
    # Split on first period followed by whitespace or end of string.
    m = re.search(r"\.(?:\s|$)", text)
    if m:
        return text[: m.start() + 1].strip()
    return text.strip()


def generate_manifest() -> int:
    """Walk conventions/*.json and emit docs/ops/verb-manifest.md."""
    from collections import defaultdict

    by_family: dict = defaultdict(list)

    for json_file in sorted(HERE.glob("*.json")):
        try:
            d = json.loads(json_file.read_text())
        except Exception as e:
            print(f"WARNING: could not parse {json_file.name}: {e}", file=sys.stderr)
            continue

        family = d.get("family", "")
        if family not in SOUL_FAMILIES:
            continue

        op = d.get("operation", json_file.stem)
        description = d.get("description", "")
        sigs = d.get("call_signatures", [])
        first_sig = sigs[0] if sigs else ""

        first_sent = _first_sentence(description)
        by_family[family].append((op, first_sent, first_sig))

    lines = [
        "# FreeSO Embodiment — Verb Manifest",
        "",
        "Soul-relevant verbs grouped by family.",
        "Format: `verb-name — first sentence of description. EXAMPLE: first call_signature`",
        "",
        "_Generated by `python3 FreeSO/TSOClient/FSO.Bot.Sidecar/conventions/_gen.py --manifest`._",
        "_Do not edit by hand._",
        "",
    ]

    total_verbs = 0
    for family in FAMILY_ORDER:
        entries = by_family.get(family, [])
        if not entries:
            continue
        display_name = family.replace("-", " ").title()
        lines.append(f"## {display_name}")
        lines.append("")
        for op, first_sent, first_sig in sorted(entries, key=lambda x: x[0]):
            if first_sig:
                lines.append(f"`{op}` — {first_sent} EXAMPLE: `{first_sig}`")
            else:
                lines.append(f"`{op}` — {first_sent}")
            total_verbs += 1
        lines.append("")

    # Emit any soul families not in FAMILY_ORDER (e.g. "naming" if populated).
    for family in sorted(by_family):
        if family in FAMILY_ORDER:
            continue
        entries = by_family[family]
        display_name = family.replace("-", " ").title()
        lines.append(f"## {display_name}")
        lines.append("")
        for op, first_sent, first_sig in sorted(entries, key=lambda x: x[0]):
            if first_sig:
                lines.append(f"`{op}` — {first_sent} EXAMPLE: `{first_sig}`")
            else:
                lines.append(f"`{op}` — {first_sent}")
            total_verbs += 1
        lines.append("")

    MANIFEST_OUT.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_OUT.write_text("\n".join(lines) + "\n")

    line_count = len(lines)
    print(f"wrote {MANIFEST_OUT} ({total_verbs} verbs, {line_count} lines)")
    return 0


def main():
    if "--manifest" in sys.argv:
        return generate_manifest()

    text = CATALOG.read_text()
    ops = parse_catalog(text)
    # Preserve curated declarations that already have richer arg schemas.
    curated = {"walk-to", "speak"}
    generated = 0
    for op, description, family in ops:
        if op in curated:
            continue
        write_decl(op, description, family)
        generated += 1
    print(f"generated {generated} skeletons ({len(ops)} ops total, {len(curated)} curated)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
