<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MSDFData</RootNamespace>
    <AssemblyName>MSDFData</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>True</IsAotCompatible>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>link</TrimMode>
  </PropertyGroup>

  <PropertyGroup>
    <FSOUseXnaPackages>true</FSOUseXnaPackages>
  </PropertyGroup>

</Project>
