/*
This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at
http://mozilla.org/MPL/2.0/.
*/

using System;

namespace FSO.Client.GameContent
{
  //Generated by Mr. Shipper - filenames have been sanitized, and does not match
  //actual filenames character for character!
  partial class FileIDs
  {
      public enum CollectionsFileIDs : long
      {
          costumes_female = 0x400000010,
          costumes_male = 0x300000010,
          daywear_female = 0x1C00000010,
          daywear_male = 0x1B00000010,
          eainternalheads_unisex = 0x2200000010,
          eainternal_unisex = 0x2100000010,
          ea_female = 0x1E00000010,
          ea_male = 0x1D00000010,
          formalwear_female = 0x1A00000010,
          formalwear_male = 0x1900000010,
          naked_female = 0x2000000010,
          naked_male = 0x1F00000010,
          oldworld_female = 0x600000010,
          oldworld_male = 0x500000010,
          scifi_female = 0x800000010,
          scifi_male = 0x700000010,
          sleepwear_female = 0x1600000010,
          sleepwear_male = 0x1500000010,
          sports_female = 0xA00000010,
          sports_male = 0x900000010,
          swimwear_female = 0x1800000010,
          swimwear_male = 0x1700000010,
          toga_female = 0xC00000010,
          toga_male = 0xB00000010,
          uniforms_female = 0xE00000010,
          uniforms_male = 0xD00000010,
          vaudwest_female = 0x1400000010,
          vaudwest_male = 0x1300000010,
          vegas_female = 0x1000000010,
          vegas_male = 0xF00000010,
          wedding_female = 0x1200000010,
          wedding_male = 0x1100000010,
          ea_female_heads = 0x200000010,
          ea_male_heads = 0x100000010,
          nightclub_female = 0x2800000010,
          nightclub_male = 0x2700000010,
          restaurant_female = 0x2600000010,
          restaurant_male = 0x2500000010,
          robot_female = 0x2400000010,
          robot_male = 0x2300000010,
          decor_back = 0x2A00000010,
          decor_head = 0x2900000010,
          decor_shoes = 0x2B00000010,
          decor_tail = 0x2C00000010
      };
  }
}
