using System.IO;
using System.Linq;
using FSO.Files.Formats.IFF;
using FSO.Files.Formats.IFF.Chunks;
using Newtonsoft.Json.Linq;
using Xunit;

namespace FSO.PackCompiler.Tests
{
    /// <summary>
    /// Covers appearance.generated (parametric art from ArtGen), the counterpart to
    /// AppearanceCloneTests' coverage of appearance.clone_from_guid. Unlike cloning, this
    /// path needs no base-game content directory, so all these tests run unconditionally.
    /// </summary>
    public class GeneratedAppearanceTests
    {
        private static JObject BasePack(JObject appearance)
        {
            return new JObject
            {
                ["schema"] = "fso-pack/0.1",
                ["engine"] = "tso",
                ["pack"] = new JObject { ["id"] = "generated-test", ["name"] = "Generated Test", ["version"] = "1.0.0" },
                ["objects"] = new JArray
                {
                    new JObject
                    {
                        ["id"] = "generated_chair",
                        ["guid"] = "0x6B4F0F02",
                        ["name"] = "Generated Chair",
                        ["price"] = 100,
                        ["category"] = "seating",
                        ["appearance"] = appearance,
                        ["trees"] = new JObject
                        {
                            ["main_loop"] = new JObject
                            {
                                ["args"] = new JArray(),
                                ["locals"] = new JArray(),
                                ["nodes"] = new JArray
                                {
                                    new JObject
                                    {
                                        ["id"] = "idle",
                                        ["prim"] = "idle_for_input",
                                        ["ticks_param"] = 0,
                                        ["allow_push"] = true,
                                        ["then"] = "idle",
                                        ["else"] = "idle",
                                    },
                                },
                            },
                        },
                        ["entry_points"] = new JObject { ["main"] = "main_loop" },
                    },
                },
            };
        }

        private static string WritePack(JObject pack)
        {
            var dir = TestPaths.TempDir();
            var path = Path.Combine(dir, "pack.json");
            File.WriteAllText(path, pack.ToString());
            return path;
        }

        [Fact]
        public void ChairGenerator_ProducesDgrpAndSpr2ChunksInline()
        {
            var appearance = new JObject
            {
                ["generated"] = new JObject
                {
                    ["generator"] = "chair",
                    ["params"] = new JObject { ["arms"] = true },
                },
            };
            var packPath = WritePack(BasePack(appearance));
            var outDir = TestPaths.TempDir();

            var result = PackCompilerApi.Build(packPath, outDir);
            Assert.True(result.Success, string.Join("\n", result.Diagnostics.Errors));

            var iff = new IffFile(Path.Combine(outDir, "generated_chair.iff"));

            var dgrps = iff.List<DGRP>();
            Assert.NotNull(dgrps);
            Assert.NotEmpty(dgrps);
            Assert.NotEmpty(iff.List<SPR2>());
            Assert.NotEmpty(iff.List<PALT>());

            var objd = iff.List<OBJD>().Single();
            Assert.True(objd.BaseGraphicID > 0);
            Assert.NotNull(iff.Get<DGRP>(objd.BaseGraphicID));

            // Every sprite a draw group references must resolve inside this file — the
            // constraint DGRP.GetTexture enforces via its own ChunkParent, no cross-file
            // fallback.
            foreach (var dgrp in dgrps)
                foreach (var image in dgrp.Images)
                    foreach (var sprite in image.Sprites)
                        Assert.NotNull(iff.Get<SPR2>((ushort)sprite.SpriteID));

            Assert.Contains(result.Report.Objects.Single().Notes, n => n.Contains("appearance generated by \"chair\""));
        }

        [Fact]
        public void BothCloneAndGenerated_IsError()
        {
            var appearance = new JObject
            {
                ["clone_from_guid"] = "0xC14849AC",
                ["generated"] = new JObject { ["generator"] = "chair" },
            };
            var result = PackCompilerApi.Build(WritePack(BasePack(appearance)), TestPaths.TempDir());

            Assert.False(result.Success);
            Assert.Contains(result.Diagnostics.Errors, e => e.Contains("mutually exclusive"));
        }

        [Fact]
        public void UnknownGenerator_IsError()
        {
            var appearance = new JObject
            {
                ["generated"] = new JObject { ["generator"] = "sofa" },
            };
            var result = PackCompilerApi.Build(WritePack(BasePack(appearance)), TestPaths.TempDir());

            Assert.False(result.Success);
            Assert.Contains(result.Diagnostics.Errors, e => e.Contains("unknown generator \"sofa\""));
        }

        [Fact]
        public void NonPositiveParam_IsError()
        {
            var appearance = new JObject
            {
                ["generated"] = new JObject
                {
                    ["generator"] = "chair",
                    ["params"] = new JObject { ["seat_width"] = 0 },
                },
            };
            var result = PackCompilerApi.Build(WritePack(BasePack(appearance)), TestPaths.TempDir());

            Assert.False(result.Success);
            Assert.Contains(result.Diagnostics.Errors, e => e.Contains("seat_width") && e.Contains("must be > 0"));
        }

        [Fact]
        public void UnknownParamField_IsError()
        {
            var appearance = new JObject
            {
                ["generated"] = new JObject
                {
                    ["generator"] = "chair",
                    ["params"] = new JObject { ["sparkle"] = true },
                },
            };
            var result = PackCompilerApi.Build(WritePack(BasePack(appearance)), TestPaths.TempDir());

            Assert.False(result.Success);
            Assert.Contains(result.Diagnostics.Errors, e => e.Contains("sparkle") && e.Contains("unknown field"));
        }
    }
}
