<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <RootNamespace>FSO.FsovDump</RootNamespace>
    <AssemblyName>fsov-dump</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\tso.simantics\FSO.SimAntics.csproj" />
    <ProjectReference Include="..\tso.content\FSO.Content.csproj" />
  </ItemGroup>
</Project>
