<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>FreeSO</AssemblyName>
    <RootNamespace>FSO.Mac</RootNamespace>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\tso.client\FSO.Client.csproj" />
    <ProjectReference Include="..\tso.common\FSO.Common.csproj" />
    <ProjectReference Include="..\tso.files\FSO.Files.csproj" />
  </ItemGroup>

</Project>
