<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Exe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>FSOFacadeWorker</RootNamespace>
    <AssemblyName>FSOFacadeWorker</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <TrimMode>partial</TrimMode>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="facadeconfig.sample.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.5-preview.2" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FSO.Server.Clients\FSO.Server.Clients.csproj" />
    <ProjectReference Include="..\FSO.Server\FSO.Server.csproj" />
    <ProjectReference Include="..\FSO.Windows\FSO.Windows.csproj" />
    <ProjectReference Include="..\tso.client\FSO.Client.csproj" />
    <ProjectReference Include="..\tso.common\FSO.Common.csproj" />
    <ProjectReference Include="..\tso.content\FSO.Content.csproj" />
    <ProjectReference Include="..\tso.files\FSO.Files.csproj" />
    <ProjectReference Include="..\tso.simantics\FSO.SimAntics.csproj" />
    <ProjectReference Include="..\tso.sound\FSO.HIT.csproj" />
    <ProjectReference Include="..\tso.vitaboy.engine\FSO.Vitaboy.Engine.csproj" />
    <ProjectReference Include="..\tso.vitaboy.model\FSO.Vitaboy.csproj" />
    <ProjectReference Include="..\tso.world\FSO.LotView.csproj" />
  </ItemGroup>

	<PropertyGroup>
		<NuGetGlobalPackages Condition=" '$(OS)' == 'Windows_NT' ">$(USERPROFILE)\.nuget\packages</NuGetGlobalPackages>
		<NuGetGlobalPackages Condition=" '$(OS)' != 'Windows_NT' ">$(HOME)/.nuget/packages</NuGetGlobalPackages>
	</PropertyGroup>

	<Target Name="CopyMonoGameDLLs" AfterTargets="Build">
		<!-- Remove root MonoGame.Framework.dll if it exists -->
		<Delete Files="$(OutputPath)MonoGame.Framework.dll" ContinueOnError="true" />
		<ItemGroup>
			<MGWindowsDX Include="$(NuGetGlobalPackages)\monogame.framework.windowsdx\3.8.5-preview.2\lib\**\MonoGame.Framework.dll" />
		</ItemGroup>
		<Copy SourceFiles="@(MGWindowsDX)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
	</Target>

</Project>
