using System;

namespace TSOClient
{
  //Generated by Mr. Shipper - filenames have been sanitized, and does not match
  //actual filenames character for character!
  partial class FileIDs
  {
      public enum CollectionsFileIDs : long
      {
          costumes_female = 0x0000000400000010,
          costumes_male = 0x0000000300000010,
          daywear_female = 0x0000001C00000010,
          daywear_male = 0x0000001B00000010,
          eainternalheads_unisex = 0x0000002200000010,
          eainternal_unisex = 0x0000002100000010,
          ea_female = 0x0000001E00000010,
          ea_male = 0x0000001D00000010,
          formalwear_female = 0x0000001A00000010,
          formalwear_male = 0x0000001900000010,
          naked_female = 0x0000002000000010,
          naked_male = 0x0000001F00000010,
          oldworld_female = 0x0000000600000010,
          oldworld_male = 0x0000000500000010,
          scifi_female = 0x0000000800000010,
          scifi_male = 0x0000000700000010,
          sleepwear_female = 0x0000001600000010,
          sleepwear_male = 0x0000001500000010,
          sports_female = 0x0000000A00000010,
          sports_male = 0x0000000900000010,
          swimwear_female = 0x0000001800000010,
          swimwear_male = 0x0000001700000010,
          toga_female = 0x0000000C00000010,
          toga_male = 0x0000000B00000010,
          uniforms_female = 0x0000000E00000010,
          uniforms_male = 0x0000000D00000010,
          vaudwest_female = 0x0000001400000010,
          vaudwest_male = 0x0000001300000010,
          vegas_female = 0x0000001000000010,
          vegas_male = 0x0000000F00000010,
          wedding_female = 0x0000001200000010,
          wedding_male = 0x0000001100000010,
          ea_female_heads = 0x0000000200000010,
          ea_male_heads = 0x0000000100000010,
          nightclub_female = 0x0000002800000010,
          nightclub_male = 0x0000002700000010,
          restaurant_female = 0x0000002600000010,
          restaurant_male = 0x0000002500000010,
          robot_female = 0x0000002400000010,
          robot_male = 0x0000002300000010,
          decor_back = 0x0000002A00000010,
          decor_head = 0x0000002900000010,
          decor_shoes = 0x0000002B00000010,
          decor_tail = 0x0000002C00000010
      };
  }
}
