using System;

namespace TSOClient
{
  //Generated by Mr. Shipper - filenames have been sanitized, and does not match
  //actual filenames character for character!
  partial class FileIDs
  {
      public enum HandgroupsFileIDs : long
      {
          fam_bears = 0x0000002500000012,
          fam_bride01 = 0x0000000100000012,
          fam_bride03 = 0x0000000200000012,
          fam_bride04 = 0x0000000300000012,
          fam_bride05 = 0x0000000400000012,
          fam_burgler = 0x0000001B00000012,
          fam_cfg = 0x0000000500000012,
          fam_dancer_pinkg = 0x0000001C00000012,
          fam_default = 0x0000000600000012,
          fam_dresssade = 0x0000001700000012,
          fam_mads = 0x0000000700000012,
          fam_mnst = 0x0000001500000012,
          fam_monkey = 0x0000000800000012,
          fam_mountie = 0x0000000900000012,
          fam_polarbear = 0x0000002600000012,
          fam_proxy = 0x0000001800000012,
          fam_purpgorilla = 0x0000002700000012,
          fam_robot = 0x0000002B00000012,
          fam_shebie = 0x0000002800000012,
          fam_skelnegative = 0x0000002D00000012,
          fam_skelnormal = 0x0000002E00000012,
          fam_strip = 0x0000001D00000012,
          fam_stripblue = 0x0000001E00000012,
          fam_stripgreen = 0x0000001F00000012,
          fam_tpac = 0x0000000A00000012,
          mam_bride01 = 0x0000000B00000012,
          mam_bride03 = 0x0000000C00000012,
          mam_bride04 = 0x0000000D00000012,
          mam_bride05 = 0x0000000E00000012,
          mam_burgler = 0x0000002000000012,
          mam_cfg = 0x0000000F00000012,
          mam_dancer_pinkg = 0x0000002100000012,
          mam_default = 0x0000001000000012,
          mam_dresssade = 0x0000001900000012,
          mam_mads = 0x0000001100000012,
          mam_mnst = 0x0000001600000012,
          mam_monkey = 0x0000001200000012,
          mam_mountie = 0x0000001300000012,
          mam_proxy = 0x0000001A00000012,
          mam_purpgorilla = 0x0000002900000012,
          mam_robot = 0x0000002C00000012,
          mam_shebie = 0x0000002A00000012,
          mam_skelnegative = 0x0000002F00000012,
          mam_skelnormal = 0x0000003000000012,
          mam_strip = 0x0000002200000012,
          mam_stripblue = 0x0000002300000012,
          mam_stripgreen = 0x0000002400000012,
          mam_tpac = 0x0000001400000012
      };
  }
}
