using System;

namespace TSOClient
{
  //Generated by Mr. Shipper - filenames have been sanitized, and does not match
  //actual filenames character for character!
  partial class FileIDs
  {
      public enum HandgroupsFileIDs : long
      {
          fam_bears = 0x2500000012,
          fam_bride01 = 0x100000012,
          fam_bride03 = 0x200000012,
          fam_bride04 = 0x300000012,
          fam_bride05 = 0x400000012,
          fam_burgler = 0x1B00000012,
          fam_cfg = 0x500000012,
          fam_dancer_pinkg = 0x1C00000012,
          fam_default = 0x600000012,
          fam_dresssade = 0x1700000012,
          fam_mads = 0x700000012,
          fam_mnst = 0x1500000012,
          fam_monkey = 0x800000012,
          fam_mountie = 0x900000012,
          fam_polarbear = 0x2600000012,
          fam_proxy = 0x1800000012,
          fam_purpgorilla = 0x2700000012,
          fam_robot = 0x2B00000012,
          fam_shebie = 0x2800000012,
          fam_skelnegative = 0x2D00000012,
          fam_skelnormal = 0x2E00000012,
          fam_strip = 0x1D00000012,
          fam_stripblue = 0x1E00000012,
          fam_stripgreen = 0x1F00000012,
          fam_tpac = 0xA00000012,
          mam_bride01 = 0xB00000012,
          mam_bride03 = 0xC00000012,
          mam_bride04 = 0xD00000012,
          mam_bride05 = 0xE00000012,
          mam_burgler = 0x2000000012,
          mam_cfg = 0xF00000012,
          mam_dancer_pinkg = 0x2100000012,
          mam_default = 0x1000000012,
          mam_dresssade = 0x1900000012,
          mam_mads = 0x1100000012,
          mam_mnst = 0x1600000012,
          mam_monkey = 0x1200000012,
          mam_mountie = 0x1300000012,
          mam_proxy = 0x1A00000012,
          mam_purpgorilla = 0x2900000012,
          mam_robot = 0x2C00000012,
          mam_shebie = 0x2A00000012,
          mam_skelnegative = 0x2F00000012,
          mam_skelnormal = 0x3000000012,
          mam_strip = 0x2200000012,
          mam_stripblue = 0x2300000012,
          mam_stripgreen = 0x2400000012,
          mam_tpac = 0x1400000012
      };
  }
}
