/*
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/. 
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FSO.SimAntics.Model
{
    public enum VMPersonDataVariable {
        /** Standing, sitting, kneeling **/
        Posture = 0,
        MoneyAmmountOverHead = 1,
        NicePersonality = 2,
        ActivePersonality = 3,
        GenerousPersonality = 4,
        PlayfulPersonality = 5,
        OutgoingPersonality = 6,
        NeatPersonality = 7,
        CurrentOutfit = 8,
        SkillEfficiency = 9,
        CookingSkill = 10,
        CharismaSkill = 11,
        MechanicalSkill = 12,
        NetworkID = 13,
        OnlineStatus = 14,
        CreativitySkill = 15,
        CustomOutfitIndex = 16,
        BodySkill = 17,
        LogicSkill = 18,
        /** This is actually used ¬_¬, open fridge no food uses it in fridges **/
        UnusedAndDoNotUse = 19,
        AllowedSocialAndPuppeteering = 20,
        IsHousemate = 21,
        HandGestureLeft = 22,
        HandGestureRight = 23,
        JobData = 24,
        TreeUseDataField = 25,
        ChatBaloonOn = 26,
        TickCounter = 27,
        TreeUseDataField2 = 28,
        Cheats = 29,
        CensorshipFlags = 30,
        NeighborId = 31,
        PersonType = 32,
        Priority = 33,
        GreetStatus = 34,
        VisitorSchedule = 35,
        AutonomyLevel = 36,
        RouteEntryFlags = 37,
        MultipleRoutes = 38,
        RoutingComplete = 39,
        WalkingUpStairs = 40,
        HeadSeekObject = 41,
        HeadSeekState = 42,
        HeadSeekFinishAction = 43,
        HeadSeekLimitAction = 44,
        HeadSeekTimeout = 45,
        Interest_TravelToys = 46,
        Interest_ViolenceAliens = 47,
        Interest_PoliticsPets = 48,
        Interest_SixtiesSchool = 49,
        Interest_Weather = 50,
        Interest_Sports = 51,
        Interest_Music = 52,
        Interest_Outdoors = 53,
        UnusedAndDoNotUse2 = 54,
        UnusedAndDoNotUse3 = 55,
        JobType = 56,
        JobPromotionLevel = 57,
        PersonsAge = 58,
        InteractionStatus = 59,
        SkinColor = 60,
        IncomingFriends = 61,
        TS1FamilyNumber = 61,
        RouteResult = 62,
        JobPerformance = 63,
        IsSwimming = 64,
        Gender = 65,
        Private = 66,
        LingeringHouseNumber = 67,
        IsGhost = 68,
        ChatColor = 69,
        TS1LastDayAtWork = 69,
        SkillLock = 70,
        TS1Zodiac = 70,
        NonInterruptable = 71,
        RouteFootprintMask = 72,
        FootprintExtension = 73,
        RenderDisplayFlags = 74,
        SocialTargetID = 75,
        CurrentObject = 76,
        HatID = 77,
        DecorationFlags = 78,
        DecorationDirtyFlags = 79,
        InteractionMask = 80,
        SkillLockBase = 81,
        SkillLockBody = 81,
        SkillLockCharisma = 82,
        SkillLockCooking = 83,
        SkillLockCreativity = 84,
        SkillLockLogic = 85,
        SkillLockMechanical = 86,
        DeathTicker = 87,
        GardenerRehireTicker = 88,
        MaidRehireTicker = 89,
        RepairmanRehireTicker = 90,
        OnlineJobID = 91,
        OnlineJobGrade = 92,
        OnlineJobXP = 93,
        OnlineJobSickDays = 94,
        RandomSkinIndex = 95,
        RandomHeadIndex = 96,
        RandomSkinColor = 97,
        OnlineJobStatusFlags = 98,
        NumOutgoingFriends = 99,
        BadgeLevel = 100,

        TS1FamPreference = 75,
        TS1MalePreference = 76,
        TS1AutoFollow = 77,
        TS1FreezeIdle = 78,
        TS1SocAvailabilityFlags = 79,
        TS1FameScore = 80,
        TS1FameStarPower = 81,
        TS1FameStarHighWatermark = 82,
        TS1MagicTransgressions = 83,
        TS1LivingGhost = 84,
        TS1ScalingSim = 85,
        TS1IsToad = 86,
        TS1AtWorkSchool = 87,
    }
}
