using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TSO.Simantics.model
{
    public enum VMOBJDVariable {
        Version1 = 0,
        Version2 = 1,
        InitialStackSize = 2,
        BaseGraphic = 3,
        NumGraphics = 4,
        MainTreeID = 5,
        GardeningTreeID = 6,
        TreeTableID = 7,
        IntersectionGroup = 8,
        Type = 9,
        MasterID = 10,
        SubIndex = 11,
        WashHandsTreeID = 12,
        AnimTableID = 13,
        GUID1 = 14,
        GUID2 = 15,
        Disabled = 16,
        PortalTreeID = 17,
        Price = 18,
        BodyStringsID = 19,
        SlotsID = 20,
        AllowIntersectionTreeID = 21,
        UsesFnTable = 22,
        Bitfield1 = 23,
        PrepareFoodTreeID = 24,
        CookFoodTreeID = 25,
        PlaceOnSurfaceTreeID = 26,
        DisposeTreeID = 27,
        EatFoodTreeID = 28,
        PickupFromSlotTreeID = 29,
        WashDishTreeID = 30,
        EatingSurfaceTreeID = 31,
        SitTreeID = 32,
        StandTreeID = 33,
        SalePrice = 34,
        Unused35 = 35,
        Unused36 = 36,
        BrokenBaseGraphicOffset = 37,
        Unused38 = 38,
        HasCriticalAttributes = 39,
        BuyModeType = 40,
        CatalogStringsID = 41,
        IsGlobalSimObject = 42,
        InitTreeID = 43,
        PlaceTreeID = 44,
        UserPickupTreeID = 45,
        WallStyle = 46,
        LoadTreeID = 47,
        UserPlaceTreeID = 48,
        ObjectVersion = 49,
        RoomChangedTreeID = 50,
        MotiveEffectsID = 51,
        CleanupTreeID = 52,
        LevelInfoRequestTreeID = 53,
        CatalogPopupID = 54,
        ServingSurfaceTreeID = 55,
        LevelOffset = 56,
        Shadow = 57,
        NumAttributes = 58,
        CleanTreeID = 59,
        QueueSkippedTreeID = 60,
        FrontDirection = 61,
        WallAdjacencyChangedTreeID = 62,
        MyLeadObject = 63,
        DynamicSpritesBaseID = 64,
        NumDynamicSprites = 65,
        ChairEntryFlags = 66,
        TileWidth = 67,
        LotCategories = 68,
        BuildModeType = 69,
        OriginalGUID1 = 70,
        OriginalGUID2 = 71,
        SuitGUID1 = 72,
        SuitGUID2 = 73,
        PickupTreeID = 74,
        ThumbnailGraphic = 75,
        ShadowFlags = 76,
        FootprintMask = 77,
        DynamicMultiTileUpdateTreeID = 78,
        ShadowBrightness = 79,
        RepairTreeID = 80,
        WallStyleSpriteID = 81,
        RatingHunger = 82,
        RatingComfort = 83,
        RatingHygiene = 84,
        RatingBladder = 85,
        RatingEnergy = 86,
        RatingFun = 87,
        RatingRoom = 88,
        RatingSkillFlags = 89,
        NumTypeAttributes = 90,
        MiscFlags = 91,
        TypeAttrGUID1 = 92,
        TypeAttrGUID2 = 93,
        InteractionResultStrings = 94,
        ClientHouseJoinTreeID = 95,
        PrepareForSaleTreeID = 96


    }
}
