<?xml version="1.0" encoding="utf-8"?>
<Database Name="TSO" Class="TSODataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\TSO.mdf;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="TSO_LoginServer.Properties.Settings" SettingsPropertyName="TSOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Accounts" Member="Accounts">
    <Type Name="Account">
      <Column Name="AccountID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NumCharacters" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Character1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Character2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Character3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Character_Account" Member="Character" ThisKey="Character1" OtherKey="CharacterID" Type="Character" IsForeignKey="true" />
      <Association Name="Character_Account1" Member="Character4" ThisKey="Character2" OtherKey="CharacterID" Type="Character" IsForeignKey="true" />
      <Association Name="Character_Account2" Member="Character5" ThisKey="Character3" OtherKey="CharacterID" Type="Character" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Characters" Member="Characters">
    <Type Name="Character">
      <Column Name="CharacterID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GUID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastCached" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Character_Account" Member="Accounts" ThisKey="CharacterID" OtherKey="Character1" Type="Account" />
      <Association Name="Character_Account1" Member="Accounts1" ThisKey="CharacterID" OtherKey="Character2" Type="Account" />
      <Association Name="Character_Account2" Member="Accounts2" ThisKey="CharacterID" OtherKey="Character3" Type="Account" />
    </Type>
  </Table>
</Database>