using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using CASOutfitImporter.Importer;

namespace CASOutfitImporter.Packaging
{
    internal static class PackageBuilder
    {
        public static string BuildZip(string stagingRoot, string outputZip)
        {
            if (File.Exists(outputZip)) File.Delete(outputZip);
            ZipFile.CreateFromDirectory(stagingRoot, outputZip, CompressionLevel.Optimal,
                includeBaseDirectory: false);
            return outputZip;
        }

        public static void WriteReadme(string stagingRoot, IList<ImportResult> results)
        {
            var hasCas    = results.Any(r => r.Mode == ImportMode.Cas);
            var hasTrunk  = results.Any(r => r.Mode == ImportMode.TrunkWedding);
            var anyShadowing = results.Any(r => !r.MergedWithSource);

            var sb = new StringBuilder();
            sb.AppendLine("# FreeSO Avatar Pack");
            sb.AppendLine();
            if (hasCas && !hasTrunk)
                sb.AppendLine("Adds new selectable head(s)/body(s) to Create-A-Sim.");
            else if (hasTrunk && !hasCas)
                sb.AppendLine("Adds new outfit(s) wearable at the wedding trunk.");
            else
                sb.AppendLine("Mixed pack: CAS selectables and donnable trunk outfit(s).");
            sb.AppendLine();
            sb.AppendLine("Generated by `CASOutfitImporter`.");
            sb.AppendLine();

            // ---- Manifest ----
            sb.AppendLine("## What's inside");
            sb.AppendLine();
            foreach (var r in results)
            {
                string modeDesc = r.Mode switch
                {
                    ImportMode.Cas => "CAS selectable",
                    ImportMode.TrunkWedding => "Wedding trunk outfit",
                    _ => r.Mode.ToString()
                };
                string mergeNote = r.MergedWithSource
                    ? $" (merged with existing collection, {r.CollectionEntryCount} total entries)"
                    : "";
                sb.AppendLine($"- {modeDesc}: outfit `{r.Outfit.PackedId:X16}` → `{r.CollectionName}`{mergeNote}");
            }
            sb.AppendLine();
            sb.AppendLine("Files (relative to your install root):");
            sb.AppendLine();
            sb.AppendLine("```");
            foreach (var rel in results.SelectMany(r => r.WrittenFiles).Distinct().OrderBy(s => s))
                sb.AppendLine(rel);
            sb.AppendLine("```");
            sb.AppendLine();

            // ---- Install steps ----
            sb.AppendLine("## Install");
            sb.AppendLine();
            sb.AppendLine("1. Stop the FreeSO client (and the city server, if you're going to rebuild it).");
            sb.AppendLine("2. Extract this archive into your **client** install directory so that the");
            sb.AppendLine("   `Content/Avatar/...` paths land alongside the existing ones.");
            if (hasCas)
            {
                sb.AppendLine("3. Extract the same archive into your **server** install directory.");
                sb.AppendLine("   The city server's `RegistrationHandler` validates avatar creation against");
                sb.AppendLine("   the same `ea_*.col` files this pack ships, so the server must see them.");
            }
            else
            {
                sb.AppendLine("3. (Trunk-only packs) The server **does not** validate trunk outfits — it only");
                sb.AppendLine("   stores the outfit ID. The client install alone is sufficient for the outfit");
                sb.AppendLine("   to be visible and wearable in-world.");
            }
            sb.AppendLine();

            // ---- Source patch (always required for shipping a loose .col on stock FreeSO) ----
            sb.AppendLine("## Required FreeSO source patch (one line)");
            sb.AppendLine();
            sb.AppendLine("Stock FreeSO loads `Avatar/Collections/*.col` from FAR3 archives **before**");
            sb.AppendLine("loose files, so the `.col` files in this pack would be shadowed by the originals.");
            sb.AppendLine("Flip the provider order in");
            sb.AppendLine("`TSOClient/tso.content/Framework/TSOAvatarContentProvider.cs` so loose files win:");
            sb.AppendLine();
            sb.AppendLine("```diff");
            sb.AppendLine("             SetProviders(new List<IContentProvider<T>> {");
            sb.AppendLine("-                FAR,");
            sb.AppendLine("                 Files,");
            sb.AppendLine("+                FAR,");
            sb.AppendLine("                 Runtime");
            sb.AppendLine("             });");
            sb.AppendLine("```");
            sb.AppendLine();
            if (hasCas)
                sb.AppendLine("Rebuild `FSO.Content` and the projects that reference it (client + server).");
            else
                sb.AppendLine("Rebuild `FSO.Content` and `FSO.Client`. The server doesn't need a rebuild for");
            sb.AppendLine();

            // ---- Shadow warning ----
            if (anyShadowing)
            {
                sb.AppendLine("## Heads-up: this pack will hide default outfits");
                sb.AppendLine();
                sb.AppendLine("One or more entries were generated **without** `--source-collection`, so the");
                sb.AppendLine("`.col` files in this pack contain only the new entry. Once the source patch is");
                sb.AppendLine("applied, that loose file *replaces* the FAR3-archived collection — meaning the");
                sb.AppendLine("default heads/bodies/wedding-outfits for that gender/category disappear.");
                sb.AppendLine();
                sb.AppendLine("To keep the defaults plus your additions: extract the original `.col` from your");
                sb.AppendLine("FAR3 archive (using `Other/tools/FarExtractor/`) and re-run the importer with");
                sb.AppendLine("`--source-collection <path-to-extracted.col>`.");
                sb.AppendLine();
            }

            // ---- Skin-tone synthesis note (CAS only — heads, mainly) ----
            if (hasCas)
            {
                sb.AppendLine("## Skin-tone synthesis (heads only, when input ships only `lgt`)");
                sb.AppendLine();
                sb.AppendLine("TSO outfits need three skin tones. When an input folder only provides `lgt`,");
                sb.AppendLine("the importer synthesizes `med` (×0.78) and `drk` (×0.55) by multiplying RGB.");
                sb.AppendLine("Replace the `_med.png` / `_drk.png` files in `Avatar/Textures/User/` with");
                sb.AppendLine("hand-painted versions for better results.");
                sb.AppendLine();
            }

            File.WriteAllText(Path.Combine(stagingRoot, "README.md"), sb.ToString());
        }
    }
}