<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
	  <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <ApplicationIcon>../FSO.Server/FreeSO.ico</ApplicationIcon>
    <IsAotCompatible>True</IsAotCompatible>
    <PublishAot>false</PublishAot>
    <IsAotCompatible>false</IsAotCompatible>
	<SelfContained>False</SelfContained>
	<Deterministic>true</Deterministic>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
	<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="../FSO.Server/FreeSO.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FSO.Content.TSO\FSO.Content.TSO.csproj" />
    <ProjectReference Include="..\FSO.Server.Api.Core\FSO.Server.Api.Core.csproj" />
    <ProjectReference Include="..\FSO.Server\FSO.Server.csproj" />
    <ProjectReference Include="..\tso.content\FSO.Content.csproj" />
  </ItemGroup>

</Project>
