using Newtonsoft.Json;

namespace FSO.Server.Common.Config
{
    public class GithubConfig
    {
        [JsonProperty("appName")]
        public string AppName { get; set; } = "FreeSO";
        [JsonProperty("user")]
        public string User { get; set; } = "riperiperi";
        [JsonProperty("repository")]
        public string Repository { get; set; } = "FreeSO";
        [JsonProperty("clientID")]
        public string ClientID { get; set; }
        [JsonProperty("clientSecret")]
        public string ClientSecret { get; set; }

        /// <summary>
        /// Must be generated by installing the app on your user account. Browse to the /github/ API endpoint when this is null. (yes, on this server)
        /// </summary>
        [JsonProperty("accessToken")]
        public string AccessToken { get; set; }
    }
}
