namespace FSO.Server.Common.Config
{
    public class GithubConfig
    {
        public string AppName { get; set; } = "FreeSO";
        public string User { get; set; } = "riperiperi";
        public string Repository { get; set; } = "FreeSO";
        public string ClientID { get; set; }
        public string ClientSecret { get; set; }
        
        /// <summary>
        /// Must be generated by installing the app on your user account. Browse to the /github/ API endpoint when this is null. (yes, on this server)
        /// </summary>
        public string AccessToken { get; set; }
    }
}
