# Archive manifest
Name=FreeSO Archive
Description=Archived data from the official FreeSO server from December 6th, 2024.
ZipSize=1685424672
Size=2460946754
Map=0100
ZipLocation=http://localhost:8080/archive_test_2.zip
ZipHash=
LocalDir=