var namespace_free_image_a_p_i =
[
    [ "IO", "namespace_free_image_a_p_i_1_1_i_o.html", "namespace_free_image_a_p_i_1_1_i_o" ],
    [ "Metadata", "namespace_free_image_a_p_i_1_1_metadata.html", "namespace_free_image_a_p_i_1_1_metadata" ],
    [ "Plugins", "namespace_free_image_a_p_i_1_1_plugins.html", "namespace_free_image_a_p_i_1_1_plugins" ],
    [ "FreeImageBitmap", "class_free_image_a_p_i_1_1_free_image_bitmap.html", "class_free_image_a_p_i_1_1_free_image_bitmap" ],
    [ "MemoryArray< T >", "class_free_image_a_p_i_1_1_memory_array_3_01_t_01_4.html", "class_free_image_a_p_i_1_1_memory_array_3_01_t_01_4" ],
    [ "Palette", "class_free_image_a_p_i_1_1_palette.html", "class_free_image_a_p_i_1_1_palette" ],
    [ "Scanline< T >", "class_free_image_a_p_i_1_1_scanline_3_01_t_01_4.html", "class_free_image_a_p_i_1_1_scanline_3_01_t_01_4" ],
    [ "BITMAP", "struct_free_image_a_p_i_1_1_b_i_t_m_a_p.html", "struct_free_image_a_p_i_1_1_b_i_t_m_a_p" ],
    [ "BITMAPINFO", "struct_free_image_a_p_i_1_1_b_i_t_m_a_p_i_n_f_o.html", "struct_free_image_a_p_i_1_1_b_i_t_m_a_p_i_n_f_o" ],
    [ "BITMAPINFOHEADER", "struct_free_image_a_p_i_1_1_b_i_t_m_a_p_i_n_f_o_h_e_a_d_e_r.html", "struct_free_image_a_p_i_1_1_b_i_t_m_a_p_i_n_f_o_h_e_a_d_e_r" ],
    [ "FI16RGB555", "struct_free_image_a_p_i_1_1_f_i16_r_g_b555.html", "struct_free_image_a_p_i_1_1_f_i16_r_g_b555" ],
    [ "FI16RGB565", "struct_free_image_a_p_i_1_1_f_i16_r_g_b565.html", "struct_free_image_a_p_i_1_1_f_i16_r_g_b565" ],
    [ "FI1BIT", "struct_free_image_a_p_i_1_1_f_i1_b_i_t.html", "struct_free_image_a_p_i_1_1_f_i1_b_i_t" ],
    [ "FI4BIT", "struct_free_image_a_p_i_1_1_f_i4_b_i_t.html", "struct_free_image_a_p_i_1_1_f_i4_b_i_t" ],
    [ "FIBITMAP", "struct_free_image_a_p_i_1_1_f_i_b_i_t_m_a_p.html", "struct_free_image_a_p_i_1_1_f_i_b_i_t_m_a_p" ],
    [ "FICOMPLEX", "struct_free_image_a_p_i_1_1_f_i_c_o_m_p_l_e_x.html", "struct_free_image_a_p_i_1_1_f_i_c_o_m_p_l_e_x" ],
    [ "FIICCPROFILE", "struct_free_image_a_p_i_1_1_f_i_i_c_c_p_r_o_f_i_l_e.html", "struct_free_image_a_p_i_1_1_f_i_i_c_c_p_r_o_f_i_l_e" ],
    [ "FIMEMORY", "struct_free_image_a_p_i_1_1_f_i_m_e_m_o_r_y.html", "struct_free_image_a_p_i_1_1_f_i_m_e_m_o_r_y" ],
    [ "FIMETADATA", "struct_free_image_a_p_i_1_1_f_i_m_e_t_a_d_a_t_a.html", "struct_free_image_a_p_i_1_1_f_i_m_e_t_a_d_a_t_a" ],
    [ "FIMULTIBITMAP", "struct_free_image_a_p_i_1_1_f_i_m_u_l_t_i_b_i_t_m_a_p.html", "struct_free_image_a_p_i_1_1_f_i_m_u_l_t_i_b_i_t_m_a_p" ],
    [ "FIRational", "struct_free_image_a_p_i_1_1_f_i_rational.html", "struct_free_image_a_p_i_1_1_f_i_rational" ],
    [ "FIRGB16", "struct_free_image_a_p_i_1_1_f_i_r_g_b16.html", "struct_free_image_a_p_i_1_1_f_i_r_g_b16" ],
    [ "FIRGBA16", "struct_free_image_a_p_i_1_1_f_i_r_g_b_a16.html", "struct_free_image_a_p_i_1_1_f_i_r_g_b_a16" ],
    [ "FIRGBAF", "struct_free_image_a_p_i_1_1_f_i_r_g_b_a_f.html", "struct_free_image_a_p_i_1_1_f_i_r_g_b_a_f" ],
    [ "FIRGBF", "struct_free_image_a_p_i_1_1_f_i_r_g_b_f.html", "struct_free_image_a_p_i_1_1_f_i_r_g_b_f" ],
    [ "FITAG", "struct_free_image_a_p_i_1_1_f_i_t_a_g.html", "struct_free_image_a_p_i_1_1_f_i_t_a_g" ],
    [ "FIURational", "struct_free_image_a_p_i_1_1_f_i_u_rational.html", "struct_free_image_a_p_i_1_1_f_i_u_rational" ],
    [ "RGBQUAD", "struct_free_image_a_p_i_1_1_r_g_b_q_u_a_d.html", "struct_free_image_a_p_i_1_1_r_g_b_q_u_a_d" ],
    [ "RGBTRIPLE", "struct_free_image_a_p_i_1_1_r_g_b_t_r_i_p_l_e.html", "struct_free_image_a_p_i_1_1_r_g_b_t_r_i_p_l_e" ]
];