<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <RootNamespace>FSO.ContactSheet</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FSO.PackCompiler\FSO.PackCompiler.csproj" />
  </ItemGroup>

</Project>
