name: Build FreeSO

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - run: dotnet publish TSOClient/FSO.IDE -c Release /p:ContinuousIntegrationBuild=true -r win-x64 --self-contained -o Artifacts/Client
    - run: dotnet publish TSOClient/FSO.Server.Core -c Release /p:ContinuousIntegrationBuild=true -r win-x64 --self-contained -o Artifacts/Server

    - name: Upload client artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FreeSOClient
        path: Artifacts/Client

    - name: Upload server artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FreeSOServer
        path: Artifacts/Server

  create-release:
    needs: [build]
    runs-on: windows-latest
    permissions:
      contents: write
    environment:
      name: "Release"

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Download Client
      uses: actions/download-artifact@v4
      with:
        name: FreeSOClient
        path: tempUpdate/windows

    - name: Download Server
      uses: actions/download-artifact@v4
      with:
        name: FreeSOServer
        path: tempUpdate/windows-server

    - name: Building Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FSO_UPDATE_GITHUB_REPO: ${{ github.repository }}
        FSO_UPDATE_CHANNEL_URL: ${{ vars.FSO_UPDATE_CHANNEL_URL }}
        FSO_UPDATE_PUBLIC_KEY: ${{ secrets.FSO_UPDATE_PUBLIC_KEY }}
        FSO_UPDATE_PRIVATE_KEY: ${{ secrets.FSO_UPDATE_PRIVATE_KEY }}
      run: |
        dotnet run -c Release -- "../../../tempUpdate/"
      working-directory: Other/tools/FSO.UpdateBuilder
        